import type { Job } from "./types";

/**
 * Job content. Live roles come from the ATS (Supabase `jobs` table) once
 * connected; until then this file holds DRAFT examples that render only in
 * content-preview mode (dev and preview deployments). Drafts never appear in
 * production, the sitemap or JobPosting schema, so we never advertise a role
 * that does not exist.
 */
const draft = { status: "draft" as const };

export const jobs: Job[] = [
  {
    ...draft,
    slug: "senior-ml-engineer-pune-x7k2",
    id: "x7k2",
    title: "Senior ML Engineer, LLM Platform",
    roleFamily: "ai-ml",
    seniority: "senior",
    city: "pune",
    workMode: "Hybrid",
    employmentType: "FULL_TIME",
    company: { descriptor: "Series C B2B SaaS company", size: "400–600 people", disclosed: false },
    salary: { minLpa: 42, maxLpa: 55 },
    experienceYears: { min: 6, max: 10 },
    team: "Applied AI team of 8: 5 ML engineers, 2 backend engineers and a PM. Reports to the Head of AI.",
    stack: ["Python", "PyTorch", "AWS", "PostgreSQL + pgvector", "Kubernetes"],
    summary:
      "Own the retrieval and evaluation layer behind the company's AI assistant used by enterprise customers.",
    responsibilities: [
      "Design and run retrieval, reranking and generation pipelines in production",
      "Build evaluation sets and regression tests that run on every change",
      "Work with product on what the assistant should and should not do",
      "Mentor two mid-level ML engineers",
    ],
    requirements: [
      "6+ years in software or ML engineering, 2+ shipping ML to production",
      "Hands-on production experience with LLM applications or search",
      "Strong Python and software engineering fundamentals",
      "Experience designing offline and online evaluation",
    ],
    niceToHave: ["Experience with vector databases at scale", "Open-source contributions"],
    interviewStages: [
      { stage: "Emplyify recruiter screen", duration: "30 min" },
      { stage: "Technical deep-dive", duration: "60 min" },
      { stage: "Practical: evaluation design", duration: "75 min" },
      { stage: "Head of AI", duration: "45 min" },
    ],
    expectedTimelineDays: 21,
    noticePeriodMaxDays: 90,
    postedAt: "2026-10-01",
    validThrough: "2026-12-31",
  },
  {
    ...draft,
    slug: "data-engineer-hyderabad-m3p9",
    id: "m3p9",
    title: "Data Engineer, Lakehouse",
    roleFamily: "data",
    seniority: "mid",
    city: "hyderabad",
    workMode: "Hybrid",
    employmentType: "FULL_TIME",
    company: { descriptor: "Global insurance GCC", size: "1,200 people in India", disclosed: false },
    salary: { minLpa: 22, maxLpa: 32 },
    experienceYears: { min: 3, max: 6 },
    team: "Data platform squad of 6 building the group-wide lakehouse.",
    stack: ["Spark", "Databricks", "Airflow", "Azure", "SQL"],
    summary: "Build and operate pipelines that feed finance and actuarial reporting on Databricks.",
    responsibilities: [
      "Build batch and streaming pipelines on Databricks",
      "Implement data-quality checks and contracts",
      "Tune Spark jobs for cost and reliability",
    ],
    requirements: ["3+ years of data engineering", "Spark and SQL in production", "An orchestration tool such as Airflow"],
    niceToHave: ["Insurance or banking domain", "Unity Catalog"],
    interviewStages: [
      { stage: "Emplyify recruiter screen", duration: "30 min" },
      { stage: "SQL and modelling", duration: "60 min" },
      { stage: "Spark design", duration: "60 min" },
      { stage: "Engineering manager", duration: "45 min" },
    ],
    expectedTimelineDays: 18,
    noticePeriodMaxDays: 90,
    postedAt: "2026-10-01",
    validThrough: "2026-12-31",
  },
  {
    ...draft,
    slug: "platform-engineer-bengaluru-q4t1",
    id: "q4t1",
    title: "Platform Engineer, Kubernetes",
    roleFamily: "cloud-devops",
    seniority: "senior",
    city: "bengaluru",
    workMode: "Hybrid",
    employmentType: "FULL_TIME",
    company: { descriptor: "Series B logistics platform", size: "250 people", disclosed: false },
    salary: { minLpa: 35, maxLpa: 46 },
    experienceYears: { min: 6, max: 10 },
    team: "Platform team of 5 serving 60 engineers.",
    stack: ["Kubernetes (EKS)", "Terraform", "Argo CD", "Prometheus", "AWS"],
    summary: "Run and evolve the Kubernetes platform and developer tooling for the whole engineering org.",
    responsibilities: ["Operate multi-cluster EKS", "Own Terraform modules and CI/CD", "Lead incident reviews"],
    requirements: ["6+ years in infrastructure", "Production Kubernetes ownership", "Terraform at scale"],
    niceToHave: ["Service mesh", "FinOps experience"],
    interviewStages: [
      { stage: "Emplyify recruiter screen", duration: "30 min" },
      { stage: "Systems deep-dive", duration: "60 min" },
      { stage: "Incident simulation", duration: "60 min" },
      { stage: "CTO", duration: "45 min" },
    ],
    expectedTimelineDays: 18,
    noticePeriodMaxDays: 60,
    postedAt: "2026-10-01",
    validThrough: "2026-12-31",
  },
  {
    ...draft,
    slug: "full-stack-engineer-pune-r8w2",
    id: "r8w2",
    title: "Founding Full-stack Engineer",
    roleFamily: "full-stack",
    seniority: "senior",
    city: "pune",
    workMode: "On-site",
    employmentType: "FULL_TIME",
    company: { descriptor: "Seed-stage B2B startup", size: "12 people", disclosed: false },
    salary: { minLpa: 30, maxLpa: 40 },
    experienceYears: { min: 5, max: 9 },
    team: "Founding team of 4 engineers working directly with the CTO.",
    stack: ["TypeScript", "Next.js", "Node.js", "PostgreSQL", "AWS"],
    summary: "Build the core product with the founders, from customer calls to production.",
    responsibilities: ["Ship features end to end", "Shape the architecture", "Talk to customers weekly"],
    requirements: ["5+ years building web products", "React and Node.js in production", "Comfort with ambiguity"],
    niceToHave: ["Startup experience", "B2B SaaS billing or onboarding"],
    interviewStages: [
      { stage: "Emplyify recruiter screen", duration: "30 min" },
      { stage: "Pairing session", duration: "90 min" },
      { stage: "Founders", duration: "60 min" },
    ],
    expectedTimelineDays: 14,
    noticePeriodMaxDays: 60,
    postedAt: "2026-10-01",
    validThrough: "2026-12-31",
  },
  {
    ...draft,
    slug: "autosar-engineer-pune-k2v6",
    id: "k2v6",
    title: "Senior AUTOSAR Engineer",
    roleFamily: "embedded",
    seniority: "senior",
    city: "pune",
    workMode: "On-site",
    employmentType: "FULL_TIME",
    company: { descriptor: "European automotive GCC", size: "2,000 people in India", disclosed: false },
    salary: { minLpa: 24, maxLpa: 34 },
    experienceYears: { min: 6, max: 10 },
    team: "Powertrain software team of 14 across Pune and Germany.",
    stack: ["Embedded C", "Classic AUTOSAR", "Vector toolchain", "CANoe", "UDS"],
    summary: "Configure and integrate Classic AUTOSAR BSW for next-generation powertrain ECUs.",
    responsibilities: ["BSW and MCAL configuration", "Integration and testing on target", "Support ASPICE assessments"],
    requirements: ["6+ years embedded C", "3+ years Classic AUTOSAR", "CAN diagnostics"],
    niceToHave: ["ISO 26262 projects", "German language basics"],
    interviewStages: [
      { stage: "Emplyify recruiter screen", duration: "30 min" },
      { stage: "Technical round", duration: "60 min" },
      { stage: "Team lead (Germany)", duration: "45 min" },
    ],
    expectedTimelineDays: 25,
    noticePeriodMaxDays: 90,
    postedAt: "2026-10-01",
    validThrough: "2026-12-31",
  },
];
